version: '3'
services:

  db-userauth-test:
    build: ../authnet
    container_name: db-userauth-test
    networks:
      - authnet-test
    volumes:
      - db-userauth-test-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: userauth-test
      MYSQL_PASSWORD: userauth-test
      MYSQL_DATABASE: userauth-test
    restart: always

  userauth-test:
    build: ../users
    container_name: userauth-test
    depends_on:
      - db-userauth-test
    networks:
      - authnet-test
      - frontnet-test
    volumes:
      - ./reports-userauth:/reports
      - ./userauth/sequelize-docker-test-mysql.yaml:/userauth/sequelize-docker-test-mysql.yaml
      - ./userauth/test.js:/userauth/test.js
    environment:
      DEBUG: ""
      NODE_ENV: "test"
      SEQUELIZE_CONNECT: "sequelize-docker-test-mysql.yaml"
      URL_USERS_TEST: "http://localhost:3333"
    restart: always

  db-diary-test:
    build: ../frontnet
    container_name: db-diary-test
    networks:
      - frontnet-test
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: diary-test
      MYSQL_PASSWORD: diary-test
      MYSQL_DATABASE: diary-test
    volumes:
      - db-diary-test-data:/var/lib/mysql
    restart: always
  
  db-diary-mongo-test:
    image: mongo:3.6-jessie
    container_name: db-diary-mongo-test
    networks: 
      - frontnet-test
    volumes:
      - ./db-diary-mongo:/data/db

  diary-test:
    build: ../diary
    container_name: diary-test
    depends_on:
      - db-diary-test
    networks:
      - frontnet-test
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: "test"
      SEQUELIZE_CONNECT: "test/sequelize-mysql.yaml"
      USER_SERVICE_URL: "http://userauth-test:3333"
    volumes:
      - ./reports-diary:/reports
      - ../diary/test:/diaryapp/test

networks:
  frontnet-test:
    driver: bridge
  authnet-test:
    driver: bridge

volumes: 
  db-userauth-test-data: 
  db-diary-test-data: